//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_tarabaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        static Transaction emp;
        public static Transaction CreateTransaction(int ID, string NameTrans, string Status, int TitleId)
        {
            emp = new Transaction();
            emp.ID = ID;
            emp.NameTrans = NameTrans;
            emp.Status = Status;
            emp.TitleID = TitleId;
            emp.Telephone = "не задано";
            emp.Email = "не задано";
            return emp;
        }
        public int ID { get; set; }
        public string NameTrans { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public int TitleID { get; set; }
    
        public virtual Title Title { get; set; }
    }
}
